#
# 版权所有2021 Misfra team
# 根据Apache-2.0许可证，(下称“许可”);
#
# 除非符合许可，否则您不能使用此文件。
#
---
C:
  - N: STMicroelectronics
    C: 意法半导体
    F:
      - N: STM32F0
        S:
          - N: STM32F0x0 Value Line
            S:
              - N: STM32F030C6Tx
                Pa: LQFP48
                Re: STM32F030C6Tx
                RP: STM32F030C6
                Co: Arm Cortex-M0
                Fr: 48
                Ra: 4
                I: 39
                F: 32
                V:
                  A: 3.6
                  I: 2.4
                Cu:
                  L: 3.4
                  R: 250
                T:
                  A: 85
                  I: -40
                Pe:
                  - T: ADC 12-bit
                    M: 10
                  - T: I2C
                    M: 1
                  - T: IRTIM
                    M: 1
                  - T: RTC
                    M: 1
                  - T: SPI
                    M: 1
                  - T: Timer 16-bit
                    M: 5
                  - T: USART
                    M: 1
